version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:6.0.9
    ports:
      - 27017:27017
    volumes:
      - ./backend/.data/mongodb:/data/db

volumes:
  data:
