openapi: 3.0.3
info:
  title: Server API - Account Service
  description: The Restful APIs of Account Service.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /api/user/login:
    post:
      summary: Login User
      operationId: LoginUser
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id_token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
  /api/user/authorized:
    post:
      summary: Verify Access Token
      operationId: VerifyToken
      tags: [user]
      security: [BearerAuth: []]
      responses:
        "200":
          description: OK
components:
  schemas:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
