@host=http://localhost:8080
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiSHVTTjNnTWpDYldTdEhFMXBaMG56RzVEc2Y5MyIsImV4cGlyZXMiOjE3MTEyNTc0MTQuNTIzOTI3fQ.k5oBYbH-XceOP8G3RLDFuhsMaHFJ65UrM_LvBFPRUOs


### Get Project

@project_id = a55c4db1-19da-48a9-9149-6d18b08ce017

# @name getProject
GET {{host}}/api/projects/{{project_id}}
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/json


### Create Project

# @name createProject
POST {{host}}/api/projects
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Porject1",
    "owner_id": "870ec420-32a5-4dec-8715-788c8d4b20d7",
    "member_list": [],
    "status_list": [
        {
            "name": "Ininial",
            "description": "Inital State"
        }
    ],
    "status_entity": [
        {
            "user_id": "870ec420-32a5-4dec-8715-788c8d4b20d7",
            "status_name": "Ininial",
            "comment": "Alomost Done"
        }
    ]
}


### Update Project

@project_id = a55c4db1-19da-48a9-9149-6d18b08ce017

# @name updateProject
PUT {{host}}/api/projects/{{project_id}}
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Porject1",
    "owner_id": "870ec420-32a5-4dec-8715-788c8d4b20d7",
    "member_list": [],
    "status_list": [
        {
            "name": "Ininial",
            "description": "Inital State"
        }
    ],
    "status_entity": [
        {
            "user_id": "870ec420-32a5-4dec-8715-788c8d4b20d7",
            "status_name": "Ininial",
            "comment": "Not Yet"
        }
    ]
}


### Delete Project

@project_id = e21f7879-2f1e-4561-b1e3-9ec0e5f459bb

# @name getProject
DELETE {{host}}/api/projects/{{project_id}}
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/json
